#  run --name petclinic-prebuild-con pet-clinic-prebuild

FROM eclipse-temurin:17-jre-jammy
WORKDIR /app
COPY build/libs/spring-petclinic-*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
